services:
  mysql_prod:
    image: mysql:8
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 80G+lOL0?2tO
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - db_network_prod

  phpmyadmin_prod:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_prod
    restart: always
    environment:
      PMA_HOST: mysql_prod
      PMA_USER: root
      PMA_PASSWORD: 80G+lOL0?2tO
      UPLOAD_LIMIT: 2048M
    ports:
      - 8083:80
    networks:
      - db_network_prod
    depends_on:
      - mysql_prod

  mongodb_prod:
    image: mongo:latest
    container_name: mongodb_prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoprod
      MONGO_INITDB_ROOT_PASSWORD: tImp61109998
    volumes:
      - ./mongo/db:/mongo/db
    ports:
      - 27017:27017
    networks:
      - db_network_prod

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - kafka_network

volumes:
  mongodb_data:

networks:
  kafka_network:
  db_network_prod:
